### ISSUE TITLE
[BUG] CSC sensor cadence reading incorrect 

### ISSUE THREAD

**Issue by jekkos** [doudar/SmartSpin2k#545]
### Description

I have deployed the latest build that has CSC support. It seems that it's not working as it should. In zwift I see the value stuck at 70 or some value above it. The reading does work properly when I connect the bike directly to Zwift.
I have attached the logs of my training session here in attachment.

### Steps to reproduce

**Expected behavior**
To see a correct cadence reading in Zwift

**Actual behavior**
Value is stuck at 70-73 most of the time

### Additional Information

[smartspin2.log](https://github.com/doudar/SmartSpin2k/files/15030238/smartspin2.log)

**Comment by jekkos** [comment]
[smartspin2.log](https://github.com/user-attachments/files/16534753/smartspin2.log)

@eMadman I wrote you about this issue some time ago on facebook. Today I have updated to the latest firmware, but still the CSC cadence is not giving me any data back. The value is stuck to 0 always. Attached here a second logfile.
Any idea what the issue could be  @doudar ?

I did see that there were a couple of fixes related to this type of sensor. If you give me some hints I might be able to build and test this myself.

**Comment by doudar** [comment]
If you go to releases, this should be fixed on the latest build. I'll be making that an automatic update in the next 24 hours.

**Comment by doudar** [comment]
Also, if it doesn't work, please let me know.

**Comment by jekkos** [comment]
Will try again this week with the latest build but last time it did not work yet.

**Comment by jekkos** [comment]
Have tested this again, but it still doesn't work. I'll try to add a new logfile here this week. I have flashed the very last version from github. Cadence reading sticks to zero while there is power output.

**Comment by doudar** [comment]
Im guessing that this is because sensor collector is re-writing the cadence value to zero from either the connected power meter or from the connected fitness machine service.

**Comment by jekkos** [comment]
So there might still be a bug? If I connect the sensor directly to Zwift I do see power and cadence values.

**Comment by doudar** [comment]
> So there might still be a bug? If I connect the sensor directly to Zwift I do see power and cadence values.

Please send through another log with the latest firmware. I have some bandwidth to work on this today.

**Comment by doudar** [comment]
I think I'm seeing your issue. CSC INPUT isn't supported yet. Only Output. For some reason your bike doesn't send the cycling cadence out through the Cycling power service. I'll see if I can implement CSC input today. It's been on my list.

**Comment by jekkos** [comment]
Ok that would be really great!

**Comment by jekkos** [comment]
I found this branch: https://github.com/doudar/SmartSpin2k/commits/Adding-CSC if there is something I can try, let me know.

**Comment by jekkos** [comment]
Hi, is there any branch I can test? changes done here might not have made it to the master yet?

**Comment by doudar** [comment]
the current testing and unit_testing branches will connect to CSC devices. Neither are completely stable/functional, but feel free to give them a try!

**Comment by jekkos** [comment]
Anything I can help out with here?

**Comment by doudar** [comment]
> Anything I can help out with here?

I've just sent some changes to Unit_Testing. I haven't done anything other than bench testing these changes, but you can try a couple things. Compile and upload Unit_Testing. Try to load a power table (manage power table menu), home your SmartSpin2k (using calibrate in a training app), Connect your cadence sensor, and then enable use "power table for power". You should then get power output using a combination of knob position and cadence. It's not perfect (YET!), but I'm getting there. 

If you don't have a power table, here is one to try (download, unzip test.ptab, and then use "import" power table, then "load power table".

[Test.zip](https://github.com/user-attachments/files/20175905/Test.zip)

**Comment by jekkos** [comment]
I have made a build of the latest code in UNit_Testing branch. I was able to connect my cadence sensor now which is great! I'll try to generate a power table first with my Assioma Favero and do a couple of runs with it, to test if that base scenario is all stable. Once I have that then I'll try the cadence to power. 

I was looking in the web interface but have the impression the focus has shifted a bit towards the app, which I have also installed now.
